config/routes.rb
Rails.application.routes.draw do
  resources :sushi_rolls 
  root 'sushi_rolls#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sushi_roll.rb
class SushiRoll < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :sushi_rolls, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!, except: :index
  before_action :authenticate_user!
end

app/controllers/sushi_rolls_controller.rb
class SushiRollsController < ApplicationController
  before_action :set_sushi_roll, only: [:show, :edit, :update, :destroy]

  def index
    flash[:notice] = 'Welcome to your sushi order!'
    @rolls = current_user.sushi_rolls
  end

  def new
    # @roll = SushiRoll.new
    @roll = current_user.sushi_rolls.new
  end

  def create
    # render new with flash message
    @roll = current_user.sushi_rolls.new(sushi_rolls_params)
    # SushiRoll.new(sushi_rolls_params)

    respond_to do |format|
      if @roll.save
        format.html { redirect_to @roll, notice: 'Roll was successfully created.' }
        format.json { render :show, status: :created, location: @roll }
      else
        format.html { render :new }
        format.json { render json: @roll.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @roll.destroy
    redirect_to root_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_sushi_roll
    @roll = current_user.sushi_rolls.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def sushi_rolls_params
    # params.require(:sushi_rolls).permit(:name, :price, :first_ingredient, :second_ingredient)
    params.require(:sushi_roll).permit(:name, :price, :primary_ingredient, :secondary_ingredient)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sushi_rolls_helper.rb
module SushiRollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SushiTesting</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="ui container">
      <%= render(partial: 'shared/navbar') %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="ui menu">
  <div class="header item"><%= link_to 'Sushi List', root_path %></div>
  <div class="item"><%= link_to 'New Roll', new_sushi_roll_path %></div>
  <div class="item"><%= link_to 'Logout', destroy_user_session_path, method: :delete %></div>
</div>

app/views/sushi_rolls/delete.html.erb
<h1>SushiRolls#delete</h1>
<p>Find me in app/views/sushi_rolls/delete.html.erb</p>

app/views/sushi_rolls/edit.html.erb
<h1>SushiRolls#edit</h1>
<p>Find me in app/views/sushi_rolls/edit.html.erb</p>

app/views/sushi_rolls/index.html.erb
<h1>Sushi Rolls for <%= current_user.first_name %></h1>

<% if @rolls.any? %>
  <div class="ui four column doubling stackable grid container">
    <% @rolls.each do |roll| %>
      <div class="column">
        <h3 class='truncated-text'><%= roll.name %></h3>
      </div>
      <div class="column">&nbsp;</div>
      <div class="column">
        <%= link_to 'See details', sushi_roll_path(roll.id), class: 'btn btn-primary' %>
      </div>
      <div class="column">
        <%= link_to 'Delete Roll', sushi_roll_path(roll), method: :delete %>
      </div>
    <% end %>
  </div>
<% end %>

<!-- <br /><br /><br /><br /><br /><br /><br /><br />

<h4>ADMIN</h4>
<div class="ui four column doubling stackable grid container">
  <div class="column">
    <%= link_to 'New Roll', new_sushi_roll_path %>
  </div>
  <div class="column">
    b
  </div>
  <div class="column">
    c
  </div>
  <div class="column">
    d
  </div>
</div> -->

app/views/sushi_rolls/new.html.erb
<h1>Create a new roll for our list</h1>

<%#= form_for @roll, { local: true, class: "ui form"} do |form| %>
<%#= form_with(model: person, local: true, class: "ui form") do |form| %>
<%= form_with(model: @roll, local: true, id: current_user.id, class: "ui form") do |form|  %>

  <% if @roll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roll.errors.count, "error") %> prohibited this roll from being saved:</h2>
      <ul>
        <% @roll.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%#= current_user.id %>
  <%#= form.hidden_field user: current_user.id, id: :sushi_roll_name, required: true %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :name, required: true %>
  </div>
  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :price, required: true %>
  </div>
  <div class="field">
    <%= form.label :primary_ingredient %>
    <%= form.text_field :primary_ingredient, id: :sushi_roll_primary_ingredient, required: true %>
  </div>
  <div class="field">
    <%= form.label :secondary_ingredient %>
    <%= form.text_field :secondary_ingredient, id: :sushi_roll_secondary_ingredient, required: true %>
  </div>
  <div class="actions">
    <%= form.submit nil, class: "ui button primary" %>
  </div>
<% end %>

app/views/sushi_rolls/show.html.erb
<!-- <h1>Sushi Slingers</h1> -->
<!-- <p>Find me in app/views/sushi_rolls/show.html.erb</p> -->

<h1><%= @roll.name %></h1>
<h3><%= "$#{@roll.price}" %></h3>
<h3><%= @roll.primary_ingredient %> & <%= @roll.secondary_ingredient %></h3>